on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: divagando.azurecr.io
        username: ${{ secrets.acr_divagando_username }}
        password: ${{ secrets.acr_divagando_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t divagando.azurecr.io/divagando:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push divagando.azurecr.io/divagando:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_clusterdivagando_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep divagando | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace divagando`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: divagando
        container-registry-url: divagando.azurecr.io
        container-registry-username: ${{ secrets.acr_divagando_username }}
        container-registry-password: ${{ secrets.acr_divagando_password }}
        secret-name: clusterdivagdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: divagando
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          divagando.azurecr.io/divagando:${{ github.sha }}
        imagepullsecrets: |
          clusterdivagdockerauth
